- name: Gather container list
  service_mgmt_facts:
    operations_service_names: "{{ operations_service_names }}"
    operations_service_map:  "{{ operations_default_service_map|combine(operations_custom_service_map) }}"

- name: Restart containerized OpenStack services
  docker_container:
    name: "{{ item['container_name'] }}"
    state: started
    restart: yes
  loop: "{{ docker_containers }}"

- name: Restart OpenStack services
  service:
    name: "{{ item['name'] }}"
    state: restarted
  loop: "{{ systemd_services }}"
  when: item['state'] == "enabled"
