- name: Restart OpenStack services
  hosts: "{{ target_hosts | default('all') }}"
  become: yes

  tasks:
    - name: Restart services
      import_role:
        name: openstack-ops
        tasks_from: restart_service.yml
      vars:
        operations_service_map: "{{ lookup('file','library/tripleo-mapping.yaml') | from_yaml }}"
        operations_service_names: 'cinder'

